### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by gilbarbara** [gilbarbara/react-tooltips#1]
- [x] render the children in an inline element (span) with event handlers (click, mouseEnter/mouseLeave)
- [x] dispatch a callback when the handlers are triggered (and autoOpen is false)
- [x] render the tooltip on mount when open is true
- [x] calculate the offset of the children (popper)
- [x] calculate the size of the tooltip on screen (popper)
- [x] calculate the position of the tooltip and move itself to correct position (popper)
- [x] handle fixed elements (popper?)
- [x] hoverable tooltips should have a prop to change the behavior to show itself on the first mouseEnter and start a clock to hide on mouseLeave
- [x] customize arrow to any valid size (length and spread?)
- [x] add wrapper on title when it's not a react element
- [x] add wrapper to footer when it's not a react element
- [x] animate opacity closing
- [x] show a close button to hide click type and ability to disable (default: false)
- [x] test React Portal connection to the parent
